language: python

# for container-y googdness:
sudo: false

env:
  - DJANGO_VERSION=latest
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9

python:
  - "3.6"
  - "3.5"
  - "2.7"

# command to install dependencies
install: 
- "pip install --upgrade pip setuptools"
- "pip install -Ue .[test]"
- sh -c "if [ $DJANGO_VERSION = '1.10' ]; then pip install 'django<1.11'; fi"
- sh -c "if [ $DJANGO_VERSION = '1.9' ]; then pip install 'django<1.10'; fi"

# command to run tests, e.g. python setup.py test
script: coverage run -m pytest

after_success:
  - coverage combine
  - coveralls

jobs:
  include:

    - stage: coverage
      python: 3.6
      env: DJANGO_VERSION=latest
      after_success: skip

      install: "pip install -U coveralls-check"
      script: "coveralls-check $TRAVIS_COMMIT"

    - stage: release
      python: 3.6
      env: DJANGO_VERSION=latest
      script: skip

      install: "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: QrmUWPegJzGIYGI8XGY7ztjHTbpMgVDLNV6f9fjjAoo8efOubJh/BASjWD3ESPlIo1j5tGCcSRP2MN1+30zBxq7a7oiCnthISx42DP6Ih+wLHFCu7uBm12AH96hIOQUAtQotNSwB9dJAJIKKom7xkrV/nStjbcqC7hosTZlTy6o=
        on:
          tags: true
          repo: Simplistix/testfixtures
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
