group: travis_latest
dist: xenial
sudo: true
cache:
  directories:
    - $HOME/.cache/pip

language: python

env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=...
    secure: "UOGwoOV0DuItLsE4yDnnm+UnYbmNUVJ+vU+ePEN17kRkFZyF9GYg+ZXr0uCAAdMC3okVaj6QrCk3OEDlUN8YKJzBIfn3pC3DB9CRneOWLwh+/D+iE6dtjBz+2MWthPFs3YLWlJYmF2TUrcj7ZI+DBAAbnm4JftX/uJi/ndht7Lo="
  matrix:
  - DJANGO_VERSION=latest
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.9
  - MOCK_BACKPORT=true

python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:

  exclude:
  - env: DJANGO_VERSION=latest
    python: "2.7"
  - env: MOCK_BACKPORT=true
    python: "2.7"

# command to install dependencies
install: 
# remove crap from Travis image:
- "pip uninstall -y mock nose"
# make sure we have the latest and greated:
- "pip install --upgrade pip setuptools"
# install the right versions of dependencies:
- "pip install -Ue .[test]"
- sh -c "if [ $DJANGO_VERSION = '1.11' ]; then pip install -U 'django<1.12'; fi"
- sh -c "if [ $DJANGO_VERSION = '1.9' ]; then pip install -U 'django<1.10'; fi"
- sh -c "if [ ${MOCK_BACKPORT:-'false'} = 'true' ]; then pip install -U 'mock'; fi"
# show what we have:
- "pip freeze"

# command to run tests, e.g. python setup.py test
script: coverage run -m pytest

after_success:
  - coverage combine
  - "COVERALLS_PARALLEL=true coveralls"

# tell coveralls so we can ge a post back for PRs
notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:

    - stage: coverage
      if: type != pull_request
      python: 3.6
      env: DJANGO_VERSION=latest
      after_success: skip

      install: "pip install -U coveralls-check"
      script: "coveralls-check $TRAVIS_COMMIT --parallel-build-number $TRAVIS_BUILD_NUMBER --repo-token $COVERALLS_REPO_TOKEN"

    - stage: release
      if: tag IS present
      python: 3.6
      env: DJANGO_VERSION=latest
      script: skip
      # work around https://github.com/travis-ci/travis-ci/issues/8337:
      after_success: true

      install:
      - "pip install --upgrade pip setuptools"
      - "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: QrmUWPegJzGIYGI8XGY7ztjHTbpMgVDLNV6f9fjjAoo8efOubJh/BASjWD3ESPlIo1j5tGCcSRP2MN1+30zBxq7a7oiCnthISx42DP6Ih+wLHFCu7uBm12AH96hIOQUAtQotNSwB9dJAJIKKom7xkrV/nStjbcqC7hosTZlTy6o=
        on:
          tags: true
          repo: Simplistix/testfixtures
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
