group: travis_latest
dist: xenial
sudo: true
cache:
  directories:
    - $HOME/.cache/pip

language: python

env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=...
    secure: "UOGwoOV0DuItLsE4yDnnm+UnYbmNUVJ+vU+ePEN17kRkFZyF9GYg+ZXr0uCAAdMC3okVaj6QrCk3OEDlUN8YKJzBIfn3pC3DB9CRneOWLwh+/D+iE6dtjBz+2MWthPFs3YLWlJYmF2TUrcj7ZI+DBAAbnm4JftX/uJi/ndht7Lo="
  matrix:
  - DJANGO_VERSION=latest
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.9

python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:

  exclude:
  - env: DJANGO_VERSION=latest
    python: "2.7"

# command to install dependencies
install: 
- "pip install --upgrade pip setuptools"
- "pip install -Ue .[test]"
- sh -c "if [ $DJANGO_VERSION = '1.11' ]; then pip install 'django<1.12'; fi"
- sh -c "if [ $DJANGO_VERSION = '1.9' ]; then pip install 'django<1.10'; fi"

# command to run tests, e.g. python setup.py test
script: coverage run -m pytest

after_success:
  - coverage combine
  - "COVERALLS_PARALLEL=true coveralls"

notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:

    - stage: release
      if: tag IS present
      python: 3.6
      env: DJANGO_VERSION=latest
      script: skip
      # work around https://github.com/travis-ci/travis-ci/issues/8337:
      after_success: true

      install:
      - "pip install --upgrade pip setuptools"
      - "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: QrmUWPegJzGIYGI8XGY7ztjHTbpMgVDLNV6f9fjjAoo8efOubJh/BASjWD3ESPlIo1j5tGCcSRP2MN1+30zBxq7a7oiCnthISx42DP6Ih+wLHFCu7uBm12AH96hIOQUAtQotNSwB9dJAJIKKom7xkrV/nStjbcqC7hosTZlTy6o=
        on:
          tags: true
          repo: Simplistix/testfixtures
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
