name: "Release"

on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'simplistix/testfixtures' && github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tag: ${{ steps.carthorse.outputs.tag }}
    steps:
      - uses: cjw296/python-action/carthorse@v1
        id: carthorse
        with:
          tag-format: '{version}'
          check: "true"

  release:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.tag != '' }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Show tag
        run: echo "${{ toJson(needs.check.outputs) }}"
        shell: bash

      - name: Download packages from CI run
        uses: dawidd6/action-download-artifact@v9
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: Packages
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: cjw296/python-action/carthorse@v1
        with:
          tag-format: '{version}'
